### ISSUE TITLE
The result of GAP-TV algorithm on bird data is lower than that in the paper. Can you share the hyperparameters of GAP-TV used in the paper?

### ISSUE THREAD

**Issue by ucker** [liuyang12/DeSCI#3]

**Comment by liuyang12** [comment]
I think `./figures/test_desci_cassi_bird.m` could help for the `bird` simulated spectral SCI data. We use significantly more iterations for GAP-TV (250 vs 40 as in `test_desci_cassi.m`, where CAVE `toy` data is used for default). Because `bird` data does not seem to converge within tens of iterations in terms of PSNR (for simulation only). 

Generally speaking, tens of or one hundred TV iterations would be sufficient for most simulated and real data. It is one parameter could be tuned easily though.

**Comment by ucker** [comment]
Your reply helped me solve the problem. Thank you very much!
